<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Backend.fs" />
    <Compile Include="Schema.fs" />
    <Compile Include="Codec.fs" />
    <Compile Include="Refined.fs" />
    <Compile Include="TypedJson.fs" />
    <Compile Include="JsonSchemaGen.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
